fix(TCO): missing ticket_tco field in table object
pluginsGLPI/genericobject pull request #397
Opened 2024-10-25 13:34 UTC by MyvTsv

## Checklist before requesting a review

*Please delete options that are not relevant.*

- [x] I have performed a self-review of my code.
- [x] I have added tests (when available) that prove my fix is effective or that my feature works.

## Description

- It fixes !34818
- adds the ticket_tco field to the table of each object when the user wants to use tickets. This fixes the bug that prevent TCO from being calculated for genericobject.

2024-11-27 15:22 UTC, Rom1-B requested changes
It looks OK, can you get the customer to validate it?

2024-11-28 08:29 UTC, stonebuzz approved these changes

2024-12-17 09:53 UTC, Rom1-B commented on inc/type.class.php
> +
Please fix lint

2024-12-26 13:46 UTC, Rom1-B requested changes
Waiting for customer feedback.

2024-12-26 14:08 UTC, stonebuzz requested changes

2024-12-26 14:08 UTC, stonebuzz commented on CHANGELOG.md
> +- Fix: The costs associated with an item updates the TCO calculation
```suggestion
- The `TCO` (Total Cost of Ownership) is now correctly updated based on the costs associated with an item.
```

2024-12-26 14:22 UTC, stonebuzz approved these changes
Waiting for customer feedback.

2025-01-15 10:17 UTC, Rom1-B requested changes
Still awaiting validation by the client

2025-02-14 09:09 UTC, MyvTsv commented
I do not know, the client says that it does not work, but me and 2 people from Teclib tested this corrictif and claim that the patch works correctly on their side.

2025-02-14 10:27 UTC, stonebuzz commented
We'll wait for the customer to validate, keep us informed when you have news

2025-02-27 10:10 UTC, MyvTsv commented
Patch works for client

2025-03-28 10:36 UTC, Rom1-B approved these changes

2025-03-31 06:57 UTC, stonebuzz approved these changes

2025-03-31 06:57 UTC, merged